/* =========================================================================
   THE AI LAB REPORT — dataset
   Research cutoff 2026-09-25. Every figure traces to a key in SOURCES.
   null means "the company does not report this figure at the scope the field
   asks for". Nothing is modelled or invented — a dash is simply a dash.
   ========================================================================= */

const CUTOFF = "2026-09-25";

const COMPANIES = [
  {
    id: "openai",
    name: "OpenAI",
    mono: "OA",
    tagline: "General intelligence and agents",
    entity: "OpenAI corporate AI lab / company",
    cc: "US",
    country: "United States",
    hq: "San Francisco, California",
    founded: 2015,
    foundedNote: "Founded as a nonprofit in 2015; today's for-profit structure dates to 2019.",
    model: "GPT-6 Astra",
    modelDate: "2026-09-03",
    modelNote: "OpenAI's most capable model — up to a 1,050,000-token context for complex reasoning, coding, computer use and document work.",
    capability: 53,
    capabilityNote: "Artificial Analysis Intelligence Index v4.3.2, GPT-6 Astra.",
    computeGw: null,
    computeShow: ">10 GW",
    computeBasis: "Secured infrastructure milestone",
    computeNote: "April 2026: OpenAI reported surpassing 10 GW of committed AI infrastructure tied to Stargate and partners, adding more than 3 GW in 90 days. A milestone figure rather than an exact current total.",
    waterMld: null,
    waterNote: "Not reported at site level.",
    staff: 4500,
    staffStatus: "Reported",
    staffAsOf: "2026-03-21",
    staffScope: "Company-wide headcount",
    staffNote: "Reuters: about 4,500 employees (March 2026), with a stated target of 8,000 by end-2026.",
    valuation: 852,
    valuationLabel: "$852B",
    valuationType: "Post-money financing valuation",
    valuationAsOf: "2026-03-31",
    valuationStatus: "Verified / primary",
    valuationNote: "$122B round at an $852B post-money valuation; later $1.2T–$1.5T figures were fundraising discussions rather than completed rounds.",
    datacenters: "Stargate campuses + Oracle & Azure cloud",
    open: false,
    flagshipOpen: false,
    openNote: "Hosted and API only — the flagship's weights are not downloadable.",
    trainingCost: null,
    trainingHist: "≈$78.35M",
    trainingHistNote: "GPT-4 estimated compute cost (Stanford AI Index / Epoch). Applies to GPT-4, not GPT-6 Astra.",
    disclosure: { model:"y", hq:"y", founded:"y", open:"y", staff:"p", valuation:"y", capability:"n", compute:"y", water:"n" },
    note: "Scaling Stargate partnerships; holds the cohort's largest disclosed infrastructure milestone.",
    sources: ["OAI-1","OAI-2","OAI-3","OAI-4","OAI-5"],
  },
  {
    id: "anthropic",
    name: "Anthropic",
    mono: "AN",
    tagline: "Frontier models and safety research",
    entity: "Anthropic PBC",
    cc: "US",
    country: "United States",
    hq: "San Francisco, California",
    founded: 2021,
    foundedNote: "Company founded 2021 — this is not the Claude launch date.",
    model: "Claude Opus 5.5",
    modelDate: "2026-09-22",
    modelNote: "Anthropic calls Opus 5.5 its strongest model to date, leading its internal agentic-coding, computer-use and knowledge-work evaluations.",
    capability: 58,
    capabilityNote: "Artificial Analysis Intelligence Index v4.3.2, Claude Opus 5.5 — cohort leader.",
    computeGw: 5,
    computeShow: "5 GW",
    computeBasis: "Contractual upper bound (AWS)",
    computeNote: "Anthropic–Amazon agreement for up to 5 GW of new capacity, more than $100B over ten years; about 1 GW of Trainium2/3 expected online by end-2026. A contractual upper bound rather than operational capacity.",
    waterMld: null,
    waterNote: "Not reported at Anthropic's own sites; AWS reports water use at company level, a different scope.",
    staff: 4416,
    staffStatus: "Estimate",
    staffAsOf: "March 2026",
    staffScope: "Company-wide (third-party dataset)",
    staffNote: "Third-party workforce datasets place Anthropic near 4,416, with other estimates at 4,000–5,000.",
    valuation: 965,
    valuationLabel: "$965B",
    valuationType: "Post-money financing valuation (Series H)",
    valuationAsOf: "2026-05-28",
    valuationStatus: "Verified / primary",
    valuationNote: "$65B Series H at a $965B post-money valuation; a later ~$1.17T private-market indication is secondary rather than a priced round.",
    datacenters: "AWS (39 regions · 124 zones), Google Cloud, Azure",
    open: false,
    flagshipOpen: false,
    openNote: "Claude Opus 5.5 is hosted/proprietary — no downloadable weights.",
    trainingCost: null,
    trainingHist: null,
    trainingHistNote: "Anthropic has not published training-run costs for its flagship models.",
    disclosure: { model:"y", hq:"y", founded:"y", open:"y", staff:"p", valuation:"y", capability:"n", compute:"y", water:"n" },
    note: "The cohort's most detailed compute disclosure — a contractual upper bound.",
    sources: ["ANT-1","ANT-2","ANT-3"],
  },
  {
    id: "google",
    name: "Google DeepMind",
    mono: "GD",
    tagline: "Research at Google scale",
    entity: "Google DeepMind (DeepMind + Google Brain, merged 2023)",
    cc: "GB",
    country: "United Kingdom",
    hq: "London, United Kingdom",
    founded: 2010,
    foundedNote: "DeepMind's original founding; the combined Google DeepMind organization dates to April 2023.",
    model: "Gemini 3.8 Flash",
    modelDate: "2026-09-02",
    modelNote: "General-purpose flagship at the cutoff; Gemini 3.8 Audio (Sep 24) is a specialized variant, not the headline model.",
    capability: 41,
    capabilityNote: "Artificial Analysis Intelligence Index v4.3.2, Gemini 3.8 Flash.",
    computeGw: null,
    computeShow: null,
    computeBasis: null,
    computeNote: "Google's 12 GW of contracted clean energy is an energy-procurement figure; no separate AI-compute capacity is published for DeepMind.",
    waterMld: null,
    waterNote: "Google reports company-wide water use (7.7B gallons replenished ≈ 78% of 2025 freshwater use); that scope covers all Google operations rather than DeepMind sites specifically.",
    staff: 6000,
    staffStatus: "Estimate",
    staffAsOf: null,
    staffScope: "Google DeepMind (not Alphabet)",
    staffNote: "A 2026 TIME report put DeepMind near 6,000 people; the measurement date is not stated.",
    valuation: null,
    valuationLabel: null,
    valuationType: null,
    valuationAsOf: null,
    valuationStatus: "Not comparable",
    valuationNote: "No standalone Google DeepMind valuation exists. Alphabet's market capitalisation is the parent company, shown for context.",
    parentCap: 4206,
    parentName: "Alphabet",
    datacenters: "30 data-centre locations in 11 countries; AI share not published",
    open: true,
    flagshipOpen: false,
    openNote: "Ships downloadable open-weight Gemma models; the Gemini flagship itself remains closed.",
    trainingCost: null,
    trainingHist: "≈$191.4M",
    trainingHistNote: "Gemini Ultra estimated compute cost (Stanford AI Index / Epoch) — an older model, not Gemini 3.8 Flash.",
    disclosure: { model:"y", hq:"y", founded:"y", open:"y", staff:"p", valuation:"n", capability:"n", compute:"n", water:"p" },
    note: "Open at the ecosystem level (Gemma), closed at the frontier (Gemini).",
    sources: ["GDM-1","GDM-2","G-1","COST-1"],
  },
  {
    id: "meta",
    name: "Meta AI",
    mono: "MA",
    tagline: "Open models and personal agents",
    entity: "Meta AI / FAIR research organization within Meta",
    cc: "US",
    country: "United States",
    hq: "Menlo Park, California",
    founded: 2013,
    foundedNote: "FAIR launched in late 2013 — the cleanest lab-origin date; not Meta Platforms' founding.",
    model: "Muse Spark 1.3",
    modelDate: "2026-09-02",
    modelNote: "Meta describes Muse Spark as its most capable model to date; the research index lists Muse Spark 1.3 as the current frontier release.",
    capability: 48,
    capabilityNote: "Artificial Analysis Intelligence Index v4.3.2, Muse Spark 1.3.",
    computeGw: null,
    computeShow: "7 GW (parent)",
    computeBasis: "Parent-company infrastructure — not AI-only",
    computeNote: "Meta expects to deploy 7 GW of computing infrastructure in 2026 (~1 GW added in H1, 2.5 GW planned) and targets 14 GW by 2027 — Meta overall, not Meta AI-only capacity.",
    waterMld: null,
    waterNote: "Meta reports ~1.59B gallons of volumetric water benefits (2024), a restoration figure; site-level cooling water is not reported.",
    staff: 3000,
    staffStatus: "Estimate",
    staffAsOf: null,
    staffScope: "Meta AI / FAIR + GenAI organization",
    staffNote: "A 2026 workforce estimate put the broader Meta AI organization at roughly 3,000+, covering Meta AI, FAIR and the GenAI group.",
    valuation: null,
    valuationLabel: null,
    valuationType: null,
    valuationAsOf: null,
    valuationStatus: "Not comparable",
    valuationNote: "Meta AI has no standalone valuation. Meta Platforms' market capitalisation is the parent company, shown for context.",
    parentCap: 1912,
    parentName: "Meta Platforms",
    datacenters: "30 data centres reached in 2025; more under construction",
    open: true,
    flagshipOpen: false,
    openNote: "Llama weights are downloadable; the Muse flagship itself is closed.",
    trainingCost: null,
    trainingHist: "≈$3.93M",
    trainingHistNote: "Llama 2 70B estimated compute cost (Stanford AI Index / Epoch) — an older model, not Muse Spark 1.3.",
    disclosure: { model:"y", hq:"y", founded:"y", open:"y", staff:"p", valuation:"n", capability:"n", compute:"p", water:"p" },
    note: "Splits the portfolio: proprietary frontier (Muse) plus downloadable Llama weights.",
    sources: ["META-1","META-2","META-3","META-4"],
  },
  {
    id: "xai",
    name: "xAI",
    mono: "XA",
    tagline: "Real-time agents and coding",
    entity: "xAI, now inside the post-acquisition SpaceXAI structure",
    cc: "US",
    country: "United States",
    hq: "Palo Alto, California",
    founded: 2023,
    foundedNote: "X.AI CORP formed in Nevada in 2023; SEC material lists Palo Alto as its principal place of business.",
    model: "Grok 4.7",
    modelDate: "2026-09-21",
    modelNote: "xAI describes Grok 4.7 as its most capable model for coding and knowledge work.",
    capability: 46,
    capabilityNote: "Artificial Analysis Intelligence Index v4.3.2, Grok 4.7.",
    computeGw: null,
    computeShow: null,
    computeBasis: null,
    computeNote: "Colossus is xAI's identifiable AI compute footprint; no current committed capacity figure is published.",
    waterMld: null,
    waterNote: "Not reported at site level.",
    staff: 3173,
    staffStatus: "Verified",
    staffAsOf: "2026-04-30",
    staffScope: "AI segment, post-combination structure",
    staffNote: "SEC filing: 3,173 AI-segment employees as of April 30, 2026, on the post-combination scope.",
    valuation: null,
    valuationLabel: null,
    valuationType: null,
    valuationAsOf: null,
    valuationStatus: "No current price",
    valuationNote: "The combination with SpaceX changed the corporate context; no standalone priced xAI round has been completed.",
    datacenters: "Colossus campus; wider footprint not published",
    open: true,
    flagshipOpen: false,
    openNote: "Historical company line: earlier Grok weights were released. The current Grok 4.7 flagship is closed.",
    trainingCost: null,
    trainingHist: null,
    trainingHistNote: "Grok training-run costs are not published.",
    disclosure: { model:"y", hq:"y", founded:"y", open:"y", staff:"p", valuation:"p", capability:"n", compute:"n", water:"n" },
    note: "Corporate structure changed this cycle; staffing now spans an AI segment, not a standalone lab.",
    sources: ["XAI-1","XAI-2","XAI-3"],
  },
  {
    id: "mistral",
    name: "Mistral AI",
    mono: "MI",
    tagline: "Sovereign open-weight AI",
    entity: "Mistral AI (Paris)",
    cc: "FR",
    country: "France",
    hq: "Paris, France",
    founded: 2023,
    foundedNote: "Founded April 2023; the legal notice lists the Paris registered office.",
    model: "Mistral Large 3",
    modelDate: null,
    modelNote: "Mistral's own documentation describes Large 3 as an open-weight, general-purpose flagship — the cohort's cleanest open-flagship claim.",
    capability: null,
    capabilityNote: "Mistral Large 3 is not currently scored by Artificial Analysis.",
    computeGw: null,
    computeShow: "1 GW (2030 plan)",
    computeBasis: "Future plan — up to 1 GW by 2030",
    computeNote: "A strategic 2030 target of up to 1 GW, presented as a plan rather than a current figure.",
    waterMld: null,
    waterNote: "Not reported at site level.",
    staff: 1000,
    staffStatus: "Primary / reported",
    staffAsOf: null,
    staffScope: "Whole Mistral team worldwide",
    staffNote: "Mistral announced crossing 1,000 team members; the announcement carries no specific date.",
    valuation: 21,
    valuationLabel: ">€21B",
    valuationType: "Post-money financing valuation (Series D)",
    valuationAsOf: "2026-09-08",
    valuationStatus: "Verified / primary",
    valuationNote: "€3B Series D at a post-money valuation above €21B; euros are counted 1:1 with dollars.",
    datacenters: "Partner cloud; owned footprint not published",
    open: true,
    flagshipOpen: true,
    openNote: "Mistral documents Large 3 itself as open-weight — the strongest case in the cohort.",
    trainingCost: null,
    trainingHist: null,
    trainingHistNote: "Mistral has not published training-run costs.",
    disclosure: { model:"y", hq:"y", founded:"y", open:"y", staff:"p", valuation:"y", capability:"n", compute:"p", water:"n" },
    note: "Sovereign-AI positioning; newest priced round in the cohort (8 Sep 2026).",
    sources: ["MIS-1","MIS-2","MIS-3","MIS-4"],
  },
  {
    id: "deepseek",
    name: "DeepSeek",
    mono: "DS",
    tagline: "Efficient open reasoning systems",
    entity: "DeepSeek AI (Hangzhou)",
    cc: "CN",
    country: "China",
    hq: "Hangzhou, China",
    founded: 2023,
    foundedNote: "The public corporate profile says 2023 and Hangzhou; its 51–200 size bracket is shown as a bracket, not an audited figure.",
    model: "DeepSeek-V4.1-Flash",
    modelDate: "2026-09-10",
    modelNote: "Highest-current public V4 serving model: from Sep 14, V4-Pro requests were routed to V4.1-Flash until V4.1-Pro launched — which it had not, as of the cutoff.",
    capability: 39,
    capabilityNote: "Artificial Analysis Intelligence Index v4.3.2, DeepSeek-V4.1-Flash.",
    computeGw: null,
    computeShow: null,
    computeBasis: null,
    computeNote: "No current AI-compute commitment is published for DeepSeek.",
    waterMld: null,
    waterNote: "Not reported at site level.",
    staff: null,
    staffShow: "51–200 (public bracket)",
    staffStatus: null,
    staffAsOf: null,
    staffScope: null,
    staffNote: "The company says it plans to at least double staffing; the public company-size bracket is 51–200.",
    valuation: null,
    valuationLabel: null,
    valuationType: null,
    valuationAsOf: null,
    valuationStatus: "Reported, unconfirmed",
    valuationNote: "Reuters reported a prospective first round at ¥350–400B (~$52–59B) — anticipated rather than completed.",
    datacenters: "Not published",
    open: true,
    flagshipOpen: true,
    openNote: "V4-family releases ship downloadable weights, including V4.1-Flash.",
    trainingCost: null,
    trainingHist: "$5.576M",
    trainingHistNote: "DeepSeek-V3 published compute cost: 2.788M H800 GPU-hours × $2/GPU-hour. Compute-only, excluding prior research and ablations — not V4.1-Flash.",
    disclosure: { model:"y", hq:"p", founded:"y", open:"y", staff:"n", valuation:"n", capability:"n", compute:"n", water:"n" },
    note: "Publishes unusually explicit training arithmetic; current compute and valuation are not reported.",
    sources: ["DS-1","DS-2","DS-3","DS-4"],
  },
];
/* ---- Releases & moves — exactly five, this cycle --------------------- */
const RELEASES = [
  { date: "2026-09-03", id: "openai",    tag: "Launch",  tagCls: "launch",
    headline: "GPT-6 Astra launched as OpenAI's most capable model for difficult end-to-end work.", src: "OAI-1" },
  { date: "2026-09-08", id: "mistral",   tag: "Funding", tagCls: "fund",
    headline: "€3B Series D at a post-money valuation above €21B.", src: "MIS-1" },
  { date: "2026-09-10", id: "deepseek",  tag: "Release", tagCls: "launch",
    headline: "V4.1-Flash released; V4-Pro traffic routed to it until V4.1-Pro lands.", src: "DS-1" },
  { date: "2026-09-21", id: "xai",       tag: "Launch",  tagCls: "launch",
    headline: "Grok 4.7 launched as xAI's frontier model for coding and knowledge work.", src: "XAI-1" },
  { date: "2026-09-22", id: "anthropic", tag: "Launch",  tagCls: "launch",
    headline: "Claude Opus 5.5 launched as Anthropic's strongest model to date.", src: "ANT-1" },
];

/* ---- Works cited — every figure traces to one of these ---------------- */
const SOURCES = [
  { key:"OAI-1", title:"GPT-6 Astra model documentation", publisher:"OpenAI", date:"2026-09-03",
    primary:true, supports:"Flagship model, identity and capabilities",
    url:"https://developers.openai.com/api/docs/models/gpt-6-astra" },
  { key:"OAI-2", title:"Building the compute infrastructure for the Intelligence Age", publisher:"OpenAI", date:"2026-04-29",
    primary:true, supports:"Surpassed 10 GW AI-infrastructure commitment",
    url:"https://openai.com/index/building-the-compute-infrastructure-for-the-intelligence-age/" },
  { key:"OAI-3", title:"OpenAI raises $122B to accelerate the next phase of AI", publisher:"OpenAI", date:"2026-03-31",
    primary:true, supports:"$852B post-money valuation",
    url:"https://openai.com/index/accelerating-the-next-phase-ai/" },
  { key:"OAI-4", title:"Organizational structure and history", publisher:"OpenAI", date:"current",
    primary:true, supports:"2015 founding; nonprofit / for-profit structure",
    url:"https://openai.com/our-structure/" },
  { key:"OAI-5", title:"OpenAI workforce report (~4,500 staff; 8,000 target)", publisher:"Reuters", date:"2026-03-21",
    primary:false, supports:"March 2026 headcount, stale against the cutoff", url:null },
  { key:"ANT-1", title:"Introducing Claude Opus 5.5", publisher:"Anthropic", date:"2026-09-22",
    primary:true, supports:"Flagship model and launch date",
    url:"https://www.anthropic.com/claude-opus-5-5" },
  { key:"ANT-2", title:"Anthropic raises $65B Series H at $965B post-money", publisher:"Anthropic", date:"2026-05-28",
    primary:true, supports:"$965B valuation",
    url:"https://www.anthropic.com/news/series-h" },
  { key:"ANT-3", title:"Anthropic and Amazon expand collaboration for up to 5 GW", publisher:"Anthropic", date:"2026-04-20",
    primary:true, supports:"Up to 5 GW contractual compute; AWS relationship",
    url:"https://www.anthropic.com/news/anthropic-amazon-compute" },
  { key:"GDM-1", title:"About Google DeepMind", publisher:"Google DeepMind", date:"current",
    primary:true, supports:"2010 founding; 2023 DeepMind + Brain combination",
    url:"https://deepmind.google/about/" },
  { key:"GDM-2", title:"Model cards — Gemini 3.8 Flash", publisher:"Google DeepMind", date:"current",
    primary:true, supports:"Flagship model at the cutoff",
    url:"https://deepmind.google/models/model-cards/" },
  { key:"G-1", title:"2026 Environmental Report", publisher:"Google", date:"2026",
    primary:true, supports:"Company-wide freshwater replenishment of 7.7B gallons (~78% of use)",
    url:"https://sustainability.google/google-2026-environmental-report/" },
  { key:"COST-1", title:"AI Index — historical training-cost estimates", publisher:"Stanford HAI", date:"current",
    primary:false, supports:"GPT-4, Gemini Ultra and Llama 2 compute-cost references", url:null },
  { key:"META-1", title:"Introducing Muse Spark 1.3 — Meta's most capable model", publisher:"Meta AI Research", date:"2026-09-02",
    primary:true, supports:"Flagship model and positioning", url:null },
  { key:"META-2", title:"FAIR, 10 years of open science", publisher:"Meta", date:"2023-11-30",
    primary:true, supports:"FAIR launch in late 2013",
    url:"https://ai.meta.com/blog/fair-10-year-anniversary-open-science-meta/" },
  { key:"META-3", title:"Volumetric water benefits report (2024 data)", publisher:"Meta", date:"2025",
    primary:true, supports:"~1.5895B gallons of water benefits — restoration accounting", url:null },
  { key:"META-4", title:"Meta computing-capacity report (7 GW 2026; 14 GW target)", publisher:"Reuters", date:"2026-07-09",
    primary:false, supports:"Parent-company infrastructure figures, not AI-only", url:null },
  { key:"XAI-1", title:"Grok 4.7 release", publisher:"xAI", date:"2026-09-21",
    primary:true, supports:"Flagship model and launch date", url:null },
  { key:"XAI-2", title:"X.AI CORP SEC filing", publisher:"U.S. SEC", date:"2023 filing",
    primary:true, supports:"2023 formation; Palo Alto principal place of business", url:null },
  { key:"XAI-3", title:"AI-segment employee count (3,173 at 2026-04-30)", publisher:"U.S. SEC", date:"2026",
    primary:true, supports:"Post-combination AI-segment headcount", url:null },
  { key:"MIS-1", title:"Mistral raises €3B Series D at over €21B post-money", publisher:"Mistral AI", date:"2026-09-08",
    primary:true, supports:"Series D valuation",
    url:"https://mistral.ai/news/" },
  { key:"MIS-2", title:"Current models and pricing — Mistral Large 3", publisher:"Mistral AI", date:"current",
    primary:true, supports:"Open-weight flagship designation",
    url:"https://mistral.ai/pricing/api/" },
  { key:"MIS-3", title:"Compute plans — up to 1 GW by 2030", publisher:"Mistral AI", date:"2026-08-11",
    primary:true, supports:"Long-term capacity target (not current)", url:null },
  { key:"MIS-4", title:"Company history and legal notice", publisher:"Mistral AI", date:"current",
    primary:true, supports:"Paris registered office; April 2023 founding", url:null },
  { key:"DS-1", title:"DeepSeek-V4.1-Flash release and V4-Pro routing", publisher:"DeepSeek", date:"2026-09-10",
    primary:true, supports:"Flagship model at the cutoff; routing arrangement",
    url:"https://www.deepseek.com/en/news/deepseek-v4-1-flash/" },
  { key:"DS-2", title:"DeepSeek V4 Preview", publisher:"DeepSeek", date:"2026-04-24",
    primary:true, supports:"Open-weight strategy", url:null },
  { key:"DS-3", title:"Prospective DeepSeek financing (¥350–400B range)", publisher:"Reuters", date:"2026-06-03",
    primary:false, supports:"Anticipated valuation only — unconfirmed", url:null },
  { key:"DS-4", title:"DeepSeek-V3 compute cost: 2.788M H800 GPU-hours × $2", publisher:"DeepSeek technical material", date:"V3 release",
    primary:true, supports:"Published training compute arithmetic", url:null },
  { key:"AA-1", title:"Intelligence Index v4.3.2 methodology", publisher:"Artificial Analysis", date:"2026-09-07",
    primary:false, supports:"0–100 composite: agents 30 · coding 20 · science 20 · general 30",
    url:"https://artificialanalysis.ai/methodology/intelligence-benchmarking" },
  { key:"AA-2", title:"Current model leaderboard", publisher:"Artificial Analysis", date:"accessed 2026-09-25",
    primary:false, supports:"Composite scores for six of the seven flagships",
    url:"https://artificialanalysis.ai/leaderboards/models" },
  { key:"AWS-1", title:"AWS global infrastructure — 39 regions, 124 Availability Zones", publisher:"Amazon Web Services", date:"current",
    primary:true, supports:"Region and zone counts",
    url:"https://aws.amazon.com/about-aws/global-infrastructure/" },
  { key:"GDC-1", title:"Data centre locations — 30 locations in 11 countries", publisher:"Google", date:"current",
    primary:true, supports:"Google data-centre footprint; some locations hold multiple sites",
    url:"https://datacenters.google/locations" },
  { key:"AZ-1", title:"Azure global infrastructure — 60+ regions", publisher:"Microsoft Azure", date:"current",
    primary:true, supports:"Region count for the Azure network",
    url:"https://azure.microsoft.com/en-us/explore/global-infrastructure/" },
  { key:"META-5", title:"Meta data centres — 30 sites reached in 2025", publisher:"Meta", date:"2026",
    primary:true, supports:"Data-centre count; further facilities under construction",
    url:"https://datacenters.atmeta.com/" },
  { key:"OCI-1", title:"Oracle Cloud regions and global architecture", publisher:"Oracle", date:"current",
    primary:true, supports:"Global cloud-region network; builds Stargate sites for OpenAI",
    url:"https://www.oracle.com/cloud/architecture-and-regions/" },
  { key:"EQIX-1", title:"Equinix company facts — 280 facilities, 52 major projects", publisher:"Equinix", date:"2026-01",
    primary:true, supports:"Colocation facility count and development pipeline",
    url:"https://www.equinix.com/about" },
  { key:"DLR-1", title:"Digital Realty about — 300+ data centres, 55+ metro markets", publisher:"Digital Realty", date:"current",
    primary:true, supports:"Colocation data-centre count and reach",
    url:"https://www.digitalrealty.com/about" },
  { key:"WATER-1", title:"Global AI and data-centre water-use estimate, 2026", publisher:"Independent estimate", date:"2026",
    primary:false, supports:"312.5–764.6B litres/yr worldwide (82.5–202.0B US gallons), midpoint ≈538.6B litres — worldwide, not a single company", url:null },
];

/* ---- Physical infrastructure behind the labs (2026) ------------------- */
const INFRA = [
  { name: "Amazon Web Services", kind: "Hyperscaler", regions: "39", zones: "124", sites: null,
    note: "Largest region footprint in the cohort's supply chain; AWS publishes regions and zones.", src: "AWS-1" },
  { name: "Microsoft Azure", kind: "Hyperscaler", regions: "60+", zones: null, sites: null,
    note: "Global network across public-cloud services.", src: "AZ-1" },
  { name: "Google (cloud + data centres)", kind: "Hyperscaler", regions: null, zones: null, sites: "30 locations · 11 countries",
    note: "A 'location' can hold several data-centre sites.", src: "GDC-1" },
  { name: "Meta (own fleet)", kind: "Lab-run", regions: null, zones: null, sites: "30 reached in 2025",
    note: "The only cohort lab that publishes a site count; more facilities were under construction through 2025.", src: "META-5" },
  { name: "Oracle Cloud", kind: "Hyperscaler", regions: "Global network", zones: null, sites: null,
    note: "Builds and operates Stargate sites for OpenAI.", src: "OCI-1" },
  { name: "Equinix", kind: "Colocation landlord", regions: null, zones: null, sites: "280 facilities",
    note: "52 major development projects as of January 2026; rents space and power to many tenants.", src: "EQIX-1" },
  { name: "Digital Realty", kind: "Colocation landlord", regions: null, zones: null, sites: "300+ · 55+ metro areas",
    note: "Counts all multi-tenant buildings, not AI sites only.", src: "DLR-1" },
];

/* ---- Water use, worldwide — an estimate for the whole industry --------- */
const GLOBAL_WATER = {
  lo: 312.5, hi: 764.6, mid: 538.6, loGal: 82.5, hiGal: 202.0,
  scope: "Every AI and data-centre facility on Earth, for one year",
  note: "A worldwide estimate for all AI systems and the data centres that serve them — not a single company's figure.",
  src: "WATER-1",
};
/* ---- Plain-language glossary (hover any dotted word on the page) ------ */
const GLOSSARY = [
  { key: "provenance", term: "Provenance", rx: "provenance",
    def: "The record of where a number came from, so you can check it yourself.", wiki: "https://en.wikipedia.org/wiki/Provenance" },
  { key: "capability", term: "Capability index", rx: "capability index|capability",
    def: "A 0–100 score built from standard tests of an AI model's skills — coding, reasoning, tool use.", wiki: "https://en.wikipedia.org/wiki/Benchmark_(computing)" },
  { key: "aa", term: "Artificial Analysis", rx: "Artificial Analysis",
    def: "An independent testing firm. Every capability score on this dashboard comes from its tests.", wiki: null },
  { key: "gw", term: "GW — gigawatt", rx: "gigawatt|gigawatts|GW",
    def: "One billion watts. Roughly the electricity used by 750,000 homes at the same time.", wiki: "https://en.wikipedia.org/wiki/Watt" },
  { key: "mld", term: "MLD — million litres per day", rx: "million litres/day|MLD",
    def: "A water-flow rate: how many million litres a site takes in each day.", wiki: "https://en.wikipedia.org/wiki/Litre" },
  { key: "nd", term: "ND — not disclosed", rx: "ND",
    def: "Not reported — the company does not publish this figure. The field shows a dash rather than an estimate.", wiki: null },
  { key: "openweights", term: "Open weights", rx: "open weights|open-weight|open-weights",
    def: "The model file can be downloaded, so anyone can run it on their own computers.", wiki: "https://en.wikipedia.org/wiki/Open-source_artificial_intelligence" },
  { key: "flagship", term: "Flagship model", rx: "flagship",
    def: "The most capable model a lab currently offers.", wiki: null },
  { key: "postmoney", term: "Post-money valuation", rx: "post-money valuation|post-money",
    def: "What the whole company was judged to be worth right after a funding round.", wiki: "https://en.wikipedia.org/wiki/Post-money_valuation" },
  { key: "round", term: "Series H / Series D", rx: "Series H|Series D|Series A",
    def: "A funding round's label. The letter is just the order in which the rounds happened.", wiki: "https://en.wikipedia.org/wiki/Venture_round" },
  { key: "mktcap", term: "Market cap", rx: "market cap|market capitalisation",
    def: "What the stock market says a whole public company is worth: share price times all shares.", wiki: "https://en.wikipedia.org/wiki/Market_capitalization" },
  { key: "proxy", term: "Proxy", rx: "parent-company proxy|proxy",
    def: "A stand-in number. Alphabet's market cap stands in for DeepMind, which has no separate price tag.", wiki: null },
  { key: "contract", term: "Contractual upper bound", rx: "contractual upper bound|upper bound",
    def: "An 'up to this much' figure written into a contract — the ceiling, not what is running today.", wiki: null },
  { key: "median", term: "Median", rx: "median",
    def: "The middle value: half the labs sit above it, half below. One huge number cannot skew it.", wiki: "https://en.wikipedia.org/wiki/Median" },
  { key: "region", term: "Cloud region", rx: "cloud regions|cloud region",
    def: "A named cluster of data centres in one geographic area — for example 'us-east-1'.", wiki: "https://en.wikipedia.org/wiki/Cloud_computing" },
  { key: "az", term: "Availability Zone", rx: "Availability Zones|Availability Zone|AZs",
    def: "One or more separate buildings inside a cloud region, built so the others keep working if one fails.", wiki: "https://en.wikipedia.org/wiki/Availability_zone" },
  { key: "hyperscaler", term: "Hyperscaler", rx: "hyperscaler",
    def: "A company that runs cloud computing at internet scale — AWS, Microsoft, Google.", wiki: "https://en.wikipedia.org/wiki/Hyperscale_computing" },
  { key: "colo", term: "Colocation", rx: "colocation|co-location",
    def: "A data-centre landlord: it rents space and power to many different companies.", wiki: "https://en.wikipedia.org/wiki/Colocation_centre" },
  { key: "wateruse", term: "Withdrawal vs consumption", rx: "withdrawal|consumption",
    def: "Withdrawal is water taken in (most of it is returned). Consumption is water that evaporates and is gone.", wiki: "https://en.wikipedia.org/wiki/Water_footprint" },
  { key: "stargate", term: "Stargate", rx: "Stargate",
    def: "OpenAI's programme of very large data-centre campuses, built together with partners.", wiki: "https://en.wikipedia.org/wiki/Stargate_LLC" },
];

